### ISSUE TITLE
wrapper=None?

### ISSUE THREAD

**Issue by ncavedale** [vinitkumar/json2xml#55] opened 2020-05-29 17:15 UTC
When I use the 'wrapper' argument with a 'None' value, it still prints a root element:

```
JSON_DATA = readfromjson('data.json')
XML_DATA = json2xml.Json2xml(JSON_DATA, wrapper=None, pretty=True).to_xml()
print(XML_DATA)


<?xml version="1.0" ?>
<None>
  <field1 type="str">123</field1>
  <field2 type="str">abc</field2>
</None>
```

It's treating 'None' and even 'False' and 'True' as strings. Not sure if this is intentional.
Looks like a bug to me, but in any case a way to prevent creating a root element would be appreciated.
I normally use this to test for XML parsers (XML injection) on APIs by changing the json request to xml format, and many times it is not necessary to submit a root element; the backend server takes care of appending it to your request to make it a valid XML document.

**Comment by vinitkumar** [comment] 2020-05-29 17:57
Thanks for this report. I will look into it and probably push a release soon.

**Comment by vinitkumar** [comment] 2020-05-30 14:22
Hi @ncavedale. I just looked into this and the problem is that the internal library that I am calling to convert `json` to `xml`, it has a default value for wrapper set as `root`, so even if I do some changes at my end. You will still get it wrapped by `<root>`. I will keep this issue open and will probably do the change if more people want it.

**Comment by sakthigeek** [comment] 2021-05-13 05:29
@vinitkumar  It would be helpful if the option to set wrapper to None is added when no wrapper is needed.

**Comment by vinitkumar** [comment] 2022-01-29 09:46
I think this is fixed by the latest released. 

https://github.com/vinitkumar/json2xml/releases/tag/3.10.0


Please re-open if you still have issues.

**Closed by vinitkumar** 2022-01-29 09:46 UTC
Labels: bug, future
