### ISSUE TITLE
Boolean types are not converted to their XML equivalents.

### ISSUE THREAD

**Issue by jbourquin** [vinitkumar/json2xml#118] opened 2022-04-16 00:26 UTC
**Describe the bug**
When converting a JSON object with boolean type values, `Json2xml` is not converting the values to their XML equivalents. `Json2xml` should be exporting the values in the XML as the lowercase words `true` and `false` respectively. Instead, `Json2xml` is exporting them as Python boolean types using the capitalized words `True` and `False`.

**To Reproduce**
1. Given the following JSON object:

```json
{
      "boolean": true,
      "boolean_dict_list": [
        {"boolean_dict": {"boolean": true}},
        {"boolean_dict": {"boolean": false}}
      ],
      "boolean_list": [true, false]
}
```

2. Calling the `Json2xml` conversion like so:

```python
xml = json2xml.Json2xml(sample_json, pretty=True).to_xml()
```

3. Produces the following XML:

```xml
<all>
        <boolean type="bool">True</boolean>
        <boolean_dict_list type="list">
                <item type="dict">
                        <boolean_dict type="dict">
                                <boolean type="bool">True</boolean>
                        </boolean_dict>
                </item>
                <item type="dict">
                        <boolean_dict type="dict">
                                <boolean type="bool">False</boolean>
                        </boolean_dict>
                </item>
        </boolean_dict_list>
        <item type="bool">True</item>
        <item type="bool">False</item>
</all>
```
Notice all the boolean values are capitalized instead of being lowercase like they should be in XML and JSON. There also seems to be a problem with the `boolean_list` array, it is missing its parent tag.

**Expected behavior**

`Json2xml` should produce an XML string that looks like this:

```xml
<all>
        <boolean type="bool">true</boolean>
        <boolean_dict_list type="list">
                <item type="dict">
                        <boolean_dict type="dict">
                                <boolean type="bool">true</boolean>
                        </boolean_dict>
                </item>
                <item type="dict">
                        <boolean_dict type="dict">
                                <boolean type="bool">false</boolean>
                        </boolean_dict>
                </item>
        </boolean_dict_list>
        <boolean_list type="list">
            <item type="bool">true</item>
            <item type="bool">false</item>
        </boolean_list>
</all>
```

**Additional context**

The problem with the capitalized boolean values is because of the following statements in the `json2xml.dicttoxml` module:

```python
def convert(obj, ids, attr_type, item_func, cdata, item_wrap, parent="root"):
    """Routes the elements of an object to the right function to convert them
    based on their data type"""

    LOG.info(f'Inside convert(). obj type is: "{type(obj).__name__}", obj="{str(obj)}"')

    item_name = item_func(parent)

    # Booleans are converted using this function because a Python boolean is a subclass of Number
    if isinstance(obj, (numbers.Number, str)):
        return convert_kv(
            key=item_name, val=obj, attr_type=attr_type, attr={}, cdata=cdata
        )

    if hasattr(obj, "isoformat"):
        return convert_kv(
            key=item_name,
            val=obj.isoformat(),
            attr_type=attr_type,
            attr={},
            cdata=cdata,
        )

    # This is never evaluated because Python booleans are subclasses of Python integers
    if isinstance(obj, bool):
        return convert_bool(item_name, obj, attr_type, cdata)
```

Python booleans are subclasses of integers, so the boolean values are passed to `convert_kv` instead of `convert_bool` because an integer is also a `numbers.Number`. The following statements evaluate to `True` in Python:

```python
# Booleans are integers
isinstance(True, int)

# Booleans are numbers
isinstance(True, numbers.Number)

# Booleans are booleans
isinstance(True, bool)
```

**Comment by vinitkumar** [comment] 2022-04-18 07:38
@jbourquin Thanks for reporting this. I will look into fixing it. This seems to be a bug in `dicttoxml` package, but I will fix it.

**Comment by vinitkumar** [comment] 2022-04-18 07:38
@jbourquin Thanks for reporting this. I will look into fixing it. This seems to be a bug in `dicttoxml` package, but I will fix it.

**Comment by vinitkumar** [comment] 2022-04-18 09:07
@jbourquin I just released the fix for it in the pypi. https://pypi.org/project/json2xml/3.17.0/

Thank you so much for reporting the bug in such detailed manner. 🍺

**Comment by jbourquin** [comment] 2022-04-18 21:36
No problem, I'm also running into a problem with arrays that contain numbers (like booleans). 

So if I convert a JSON object that looks like this:
```json
{
      "boolean_list": [true, false],
      "number_array": [1, 2, 3],
      "string_array": ["a", "b", "c"]
}
```

It returns the following XML:
```xml
<all>
        <item type="bool">True</item>
        <item type="bool">False</item>
        <item type="int">1</item>
        <item type="int">2</item>
        <item type="int">3</item>
        <string_array type="list">
                <item type="str">a</item>
                <item type="str">b</item>
                <item type="str">c</item>
        </string_array>
</all>
```

Notice the parent elements are missing for the boolean and number arrays.

**Comment by vinitkumar** [comment] 2022-04-19 07:32
Yeah, I can reproduce it too. Would you like to send a PR to fix this?

**Comment by vinitkumar** [comment] 2022-04-19 17:02
@jbourquin please let me know if you will sending a fix for it, else I will find sometime this week and fix it.

**Comment by jbourquin** [comment] 2022-04-19 19:53
I'll take a look, but I probably won't be able to get to it before you do.

**Comment by vinitkumar** [comment] 2022-04-19 20:54
> No problem, I'm also running into a problem with arrays that contain numbers (like booleans).
> 
> So if I convert a JSON object that looks like this:
> 
> ```json
> {
>       "boolean_list": [true, false],
>       "number_array": [1, 2, 3],
>       "string_array": ["a", "b", "c"]
> }
> ```
> 
> It returns the following XML:
> 
> ```
> <all>
>         <item type="bool">True</item>
>         <item type="bool">False</item>
>         <item type="int">1</item>
>         <item type="int">2</item>
>         <item type="int">3</item>
>         <string_array type="list">
>                 <item type="str">a</item>
>                 <item type="str">b</item>
>                 <item type="str">c</item>
>         </string_array>
> </all>
> ```
> 
> Notice the parent elements are missing for the boolean and number arrays.

Just fixed and release the fix here: View at:
https://pypi.org/project/json2xml/3.17.1/

Please test and let me know if it works for you and if you are satisfied if the issue is fixd and there is no edge case remaining, please close this issue.

**Comment by jbourquin** [comment] 2022-04-20 16:54
@vinitkumar Thank you, yes this fixes my problem. I was actually working on a pull request just before your commit. Here is a unit test for these two issues if you would like to integrate it into your repository:
https://github.com/jbourquin/json2xml/blob/master/tests/test_dicttoxml.py

**Comment by vinitkumar** [comment] 2022-04-20 17:08
@jbourquin Please send me a PR with the tests and I would be more than happy to merge them if I like what I see. Thanks for your hard work.

**Comment by jbourquin** [comment] 2022-04-20 22:24
@vinitkumar I just tried installing v3.17.1 from PYPI and it seems like the old version of the `dicttoxml` module is included in the PYPI download instead of the new one with the array fix.

**Comment by vinitkumar** [comment] 2022-04-21 05:52
@jbourquin Are you sure? I just checked the code and it seems like my patch for it is there.

**Comment by vinitkumar** [comment] 2022-04-21 05:53
> @jbourquin Are you sure? I just checked the code and it seems like my patch for it is there.

Ah, I think I understand. What are you are looking for is not implemented in the latest master and has not been released yet. My last fix, made the bool lower case like `true` and `false` instead of `True` or `False`.

**Comment by jbourquin** [comment] 2022-04-21 20:01
Yeah, I'm looking for the array fix you released yesterday

**Comment by vinitkumar** [comment] 2022-04-23 16:40
A new version of json2xml is released https://pypi.org/project/json2xml/3.18.0/

Please check if that fixes your issue.

**Closed** 2022-04-25 16:15 UTC
Labels: bug, fixed
